repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all -- --check
        language: system
        files: \.rs$
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all-targets --all-features --workspace -- -D warnings
        language: system
        files: \.rs$
      - id: cargo-test
        name: cargo test
        entry: cargo test --all-features --workspace
        language: system
        files: \.rs$
        pass_filenames: false
